name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-vote:latest ./vote
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-result:latest ./result
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-worker:latest ./worker

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-vote:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-result:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-worker:latest

