name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-vote:${{ env.TAG }} ./vote
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-result:${{ env.TAG }} ./result
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-worker:${{ env.TAG }} ./worker

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-vote:${{ env.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-result:${{ env.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app-eks-worker:${{ env.TAG }}

